default-resources:
  - runtime="20h"
  - time="20:00:00"
  - nodes=1
  - cpus_per_task=10
  - ntasks=1
  - mem_mb=20000
restart-times: 3
max-jobs-per-second: 10
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
#conda-frontend: conda
  
